[RSDK-1642] Set up workflow for automatic AppImage creation
viamrobotics/rplidar pull request #22
Opened 2023-01-06 21:55 UTC by kkufieta

Ticket: https://viam.atlassian.net/browse/RSDK-1642

2023-01-06 22:03 UTC, tessavitabile requested changes

2023-01-06 22:03 UTC, tessavitabile commented on .github/workflows/appimage.yml
> +          make appimage
If you continue to use the BUILD_CHANNEL variable (which I think you can remove, if you want to), you will need to set it to "latest" here.

2023-01-06 22:04 UTC, tessavitabile commented on .github/workflows/appimage.yml
> +      - 'v[0-9]+.[0-9]+.[0-9]+'
I think you can remove the tags here, as we don't need to do tagging for this repo.

2023-01-09 19:22 UTC, closed without merging

2023-01-09 19:22 UTC, kkufieta commented
Had to close this PR and open a new one after this repo became public: https://github.com/viamrobotics/rplidar/pull/23